<a href="https://colab.research.google.com/github/MSZHabibie/tea/blob/main/Model_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# City Based Weather Analysis

In [ ]:
# importing the required libraries
import requests
# Enter the api key of openweathermap here
api_key = "81c713c1b0fea513c62681c97920daa9"
# Base url for the open map api
root_url = "http://api.openweathermap.org/data/2.5/weather?"
# Input the City name for which we need the weather data
city_name = input("Please Enter The City Name : ")
# Building the final url for the API call
url = f"{root_url}appid={api_key}&q={city_name}"
# sending a get request at the url
r = requests.get(url)
# storing the returned json data into a variable
data = r.json()
# Checking If there is no error and the status code is 200
if data['cod'] == 200:
    # getting the temperature from the json data
    temp = data['main']['temp'] - 273.15
    # getting the pressure from the json data
    pressure = data['main']['pressure']
    # getting the humidity from the json data
    humidity = data['main']['humidity']
    # getting the description from the json data
    descr = data['weather'][0]['description']
    # getting the wind speed from the json data
    wind = data['wind']['speed']
    # Displaying all the data
    print(f"City Name : {city_name}")
    print(f"The Weather Condition is {descr}")
    print(f"The temperature is {temp :.2f} Celsius")
    print(f"The pressure is {pressure}hPa")
    print(f"The humidity is {humidity}%")
    print(f"The speed of wind is {wind}m/s")
    print(url)
else:
    # If any error occured then print this
    print("Something Went Wrong")

Please Enter The City Name : jakarta
City Name : jakarta
The Weather Condition is moderate rain
The temperature is 30.80 Celsius
The pressure is 1008hPa
The humidity is 67%
The speed of wind is 3.7m/s
http://api.openweathermap.org/data/2.5/weather?appid=81c713c1b0fea513c62681c97920daa9&q=jakarta


## Improved City Based Weather Analysis but just avg Temp within month

In [ ]:
import requests
from datetime import datetime
today = datetime.today()

api_key = "81c713c1b0fea513c62681c97920daa9"

root_url = "https://history.openweathermap.org/data/2.5/aggregated/month?"

city_name = input("Please Enter The City Name : ")

url = f"{root_url}month={today.month}&q={city_name},ID&appid={api_key}"

r = requests.get(url)

data = r.json()
# Checking If there is no error and the status code is 200
if data['cod'] == 200:
    # getting the temperature from the json data
    temp = data['result']['temp']['mean'] - 273.15
    # getting the humidity from the json data
    humidity = data['result']['humidity']['mean']
    # getting the month from the json data
    month = data['result']['month']
    print(f"City Name : {city_name}")
    print(f"The avg temperature in month {month} is {temp :.2f} Celsius")
    print(f"The avg humidity in month {month} is {humidity :.2f} %")
    print(url)
else:
    message = data['message']
    print("Something Went Wrong,", message)

Please Enter The City Name : riau


KeyError: ignored

## Error handling with try except for location that has no weather history data

In [ ]:
import requests
from datetime import datetime
today = datetime.today()

api_key = "81c713c1b0fea513c62681c97920daa9"
city_name = input("Please Enter The City Name : ")

###########################################################################
# Bisa dijadikan Method #
root_url = "https://history.openweathermap.org/data/2.5/aggregated/month?"
url = f"{root_url}month={today.month}&q={city_name},ID&appid={api_key}"
r = requests.get(url)
data = r.json()

root_url2 = "https://api.openweathermap.org/data/2.5/weather?"
url2 = f"{root_url2}q={city_name}&appid={api_key}"
r2 = requests.get(url2)
data2 = r2.json()
############################################################################

# Checking If there is no error and the status code is 200
try:
  if data['cod'] == 200:
      # getting the temperature from the json data
      temp = data['result']['temp']['mean'] - 273.15
      # getting the humidity from the json data
      humidity = data['result']['humidity']['mean']
      # getting the month from the json data
      month = data['result']['month']
      print(f"City Name : {city_name}")
      print(f"The avg temperature in month {month} is {temp :.2f} Celsius")
      print(f"The avg humidity in month {month} is {humidity :.2f} %")
      print(url)
  else:
      message = data['message']
      print("Something Went Wrong,", message)
except:
  if data['code'] == 404000:
    message = data['message']
    print(f"Error, {message}. Switching to current weather....")
    # getting the temperature from the json data
    temp = data2['main']['temp'] - 273.15
    # getting the humidity from the json data
    humidity = data2['main']['humidity']
    print(f"City Name : {city_name}")
    print(f"The current temperature is {temp :.2f} Celsius")
    print(f"The current humidity is {humidity :.2f} %")
    print(url2)

Please Enter The City Name : Jakarta
City Name : Jakarta
The avg temperature in month 5 is 28.63 Celsius
The avg humidity in month 5 is 77.36 %
https://history.openweathermap.org/data/2.5/aggregated/month?month=5&q=Jakarta,ID&appid=81c713c1b0fea513c62681c97920daa9


# Dummy Dataset

In [ ]:
import pandas as pd
import numpy as np
np.random.seed(0)
data1 =pd.DataFrame({"Temperature" : np.random.uniform(20, 33, 50).round(2),
                     "Soil" : np.random.choice(range(1,4), 50, replace=True),
                     "Light" : np.random.choice(range(1,2), 50, replace=True),
                     "Label"  : "Bayam Hijau"})
data2 =pd.DataFrame({"Temperature" : np.random.uniform(20,28, 50).round(2),
                     "Soil" : np.random.choice(range(1,4), 50, replace=True),
                     "Light" : np.random.choice(range(1,2), 50, replace=True),
                     "Label"  : "Tomat"})
data3 =pd.DataFrame({"Temperature" : np.random.uniform(25,30, 50).round(2),
                     "Soil" : np.random.choice(range(1,4), 50, replace=True),
                     "Light" : np.random.choice(range(1,2), 50, replace=True),
                     "Label"  : "Kangkung"})
data4 =pd.DataFrame({"Temperature" : np.random.uniform(22,30, 50).round(2),
                     "Soil" : np.random.choice(range(1,4), 50, replace=True),
                     "Light" : np.random.choice(range(1,2), 50, replace=True),
                     "Label"  : "Terung"})
data5 =pd.DataFrame({"Temperature" : np.random.uniform(18,20, 50).round(2),
                     "Soil" : np.random.choice(range(1,4), 50, replace=True),
                     "Light" : np.random.choice(range(1,3), 50, replace=True),
                     "Label"  : "Kubis"})

In [ ]:
df = data1.append(data2, ignore_index=True).append(data3, ignore_index=True)\
            .append(data4, ignore_index=True).append(data5, ignore_index=True)
df

Temperature  Soil  Light        Label
0          27.13     2      1  Bayam Hijau
1          29.30     3      1  Bayam Hijau
2          27.84     1      1  Bayam Hijau
3          27.08     1      1  Bayam Hijau
4          25.51     3      1  Bayam Hijau
..           ...   ...    ...          ...
245        18.17     3      1        Kubis
246        18.19     2      1        Kubis
247        19.27     2      2        Kubis
248        19.90     2      2        Kubis
249        19.87     2      1        Kubis

[250 rows x 4 columns]

#test

In [ ]:
import pandas as pd

In [ ]:
# Reading the Dataset
!wget https://index.nopladi.workers.dev/0:/Crop_recommendation_2.csv
df = pd.read_csv("Crop_recommendation_2.csv")
df

--2022-05-26 04:31:18--  https://index.nopladi.workers.dev/0:/Crop_recommendation_2.csv
Resolving index.nopladi.workers.dev (index.nopladi.workers.dev)... 104.21.36.33, 172.67.184.87, 2606:4700:3031::ac43:b857, ...
Connecting to index.nopladi.workers.dev (index.nopladi.workers.dev)|104.21.36.33|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 124735 (122K) [text/csv]
Saving to: ‘Crop_recommendation_2.csv’

Crop_recommendation 100%[===================>] 121.81K  --.-KB/s    in 0.02s   

2022-05-26 04:31:20 (4.97 MB/s) - ‘Crop_recommendation_2.csv’ saved [124735/124735]



temperature   humidity        ph    rainfall   label
0       20.879744  82.002744  6.502985  202.935536    rice
1       21.770462  80.319644  7.038096  226.655537    rice
2       23.004459  82.320763  7.840207  263.964248    rice
3       26.491096  80.158363  6.980401  242.864034    rice
4       20.130175  81.604873  7.628473  262.717340    rice
...           ...        ...       ...         ...     ...
2195    26.774637  66.413269  6.780064  177.774507  coffee
2196    27.417112  56.636362  6.086922  127.924610  coffee
2197    24.131797  67.225123  6.362608  173.322839  coffee
2198    26.272418  52.127394  6.758793  127.175293  coffee
2199    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 5 columns]

# Model Creation | TensorFlow Raw

In [ ]:
import tensorflow as tf
from tensorflow.keras import layers
import pandas as pd
import numpy as np
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.utils import to_categorical

In [ ]:
X = df.iloc[:,0:3].values
y = df.iloc[:,3].values

In [ ]:
print(X[0:5])
print(y[0:5])

[[27.13  2.    1.  ]
 [29.3   3.    1.  ]
 [27.84  1.    1.  ]
 [27.08  1.    1.  ]
 [25.51  3.    1.  ]]
['Bayam Hijau' 'Bayam Hijau' 'Bayam Hijau' 'Bayam Hijau' 'Bayam Hijau']


In [ ]:
print(X.shape)
print(y.shape)

(250, 3)
(250,)


In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

In [ ]:
print(y1)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [ ]:
Y = pd.get_dummies(y1).values
print(Y[0:5])

[[1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]]


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [ ]:
print(X_train[0:5])

[[27.17  1.    1.  ]
 [24.25  2.    1.  ]
 [29.85  2.    1.  ]
 [23.59  2.    1.  ]
 [22.12  3.    1.  ]]


In [ ]:
print(y_train[0:5])

[[0 0 0 0 1]
 [0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 1]]


In [ ]:
print(X_test[0:5])

[[19.75  1.    1.  ]
 [27.26  2.    1.  ]
 [25.73  2.    1.  ]
 [29.44  1.    1.  ]
 [23.93  3.    1.  ]]


In [ ]:
print(y_test[0:5])

[[0 0 1 0 0]
 [0 1 0 0 0]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 0 0 1 0]]


In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(18, activation='relu'),
    tf.keras.layers.Dense(5, activation='softmax')
  ])
model

In [ ]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
model.fit(X_train, y_train, batch_size=50, epochs=100)

In [ ]:
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', loss)
print('Test accuracy:', accuracy)

Test loss: 1.1721851825714111
Test accuracy: 0.41999998688697815


In [ ]:
y_pred = model.predict(X_test)
y_pred

In [ ]:
actual = np.argmax(y_test,axis=1)
predicted = np.argsort(y_pred,axis=1)
print(f"Actual: {actual}")
print(f"Predicted: \n {predicted}")